### ISSUE TITLE
Is pc-skeletor available for windows?

### ISSUE THREAD

**Issue by buggogogo** [meyerls/pc-skeletor#10]
Thank you very much for your work, it helped me a lot. I wonder if pc-skeletor is available for windows?I tried installing with pip, but it didn't work.

**Comment by buggogogo** [comment]
Sorry, I read the readme carefully and found Troubleshooting

**Comment by wanghanruibaba** [comment]
Hello, can you teach me how to install and run under Windows? I can pay for consultation

**Comment by meyerls** [comment]
Please read the README file and especially the Troubleshooting section. If you have any trouble getting it to work feel free to open a new github issue.

**Comment by wanghanruibaba** [comment]
> Please read the README file and especially the Troubleshooting section. If you have any trouble getting it to work feel free to open a new github issue.

hi meyerls，Thank you for your excellent work，can you teach me how to install and run under Windows10 OS? As a beginner in programming, I would like to express my gratitude here
