### ISSUE TITLE
The version of open3d

### ISSUE THREAD

**Issue by buggogogo** [meyerls/pc-skeletor#11]
Hi, author !
I want to know the version of open3d. I tried to install pc-skeletor successfully , but it shown  " ModuleNotFoundError: No module named 'open3d.geometry' " I think it might be caused by wrong pc-skeletor version .
Thanks!

**Comment by meyerls** [comment]
Hi!

I currently use version 0.15.3 but a higher version should be okay as well. I think some problems come with python versions lower 3.7
