### ISSUE TITLE
Increase the required pytorch version

### ISSUE THREAD

**Issue by FranzEricSchneider** [meyerls/PC-Skeletor#2]
When I installed pc-skeletor to try it out I initially got a warning saying the pytorch version was too low, and 1.9.0 was required (I had 1.7.0 initially). After installing 1.9.0 I got another error when importing `pc_skeletor`. It appears `torch.asarray` was introduced in version 1.11.0. I'm not exactly sure where the 1.9.0 is specified but it should be bumped up.

Clips from the install and debug process
```
Successfully installed torch-1.9.0
AttributeError: module 'torch' has no attribute 'asarray'

Successfully installed torch-1.10.0
AttributeError: module 'torch' has no attribute 'asarray'

Successfully installed torch-1.11.0
In [1]: import torch
In [2]: torch.__version__
Out[2]: '1.11.0+cu102'
In [3]: torch.asarray
Out[3]: <function _VariableFunctionsClass.asarray>
```

Other than that things have been really easy and clear, thanks for the library!

**Comment by meyerls** [comment]
Thanks for your issue! I have solved this problem by simply not using pyTorch anymore :D
