### ISSUE TITLE
Exception point of skeleton data

### ISSUE THREAD

**Issue by pengssy1** [meyerls/pc-skeletor#21]
Hi,

I got the skeleton data using your methods. But for some individual tree skeleton data, I found some exception point. For example, the point at the red arrow. My original point cloud has not these exception point. The reason from Laplcian or else?

![6545ea4a89a112838b1e112073cb307](https://github.com/meyerls/pc-skeletor/assets/160234145/609815d5-2ce3-4b32-b348-7241a5acadaa)

Cross fingers!

**Comment by meyerls** [comment]
My first guess is that some points get contracted to some centers. I have also encountered the same behavior. My quick hack was too just delete points which all have the same coordinate (Mostly this are 100 of points in the same little region or all in (0,0,0)). What position do your points have?

**Comment by pengssy1** [comment]
These are position of exception point. So, accually, only mannualy remove these points?

![image](https://github.com/meyerls/pc-skeletor/assets/160234145/665be18a-296b-4140-80f8-3de849f054d1)

**Comment by meyerls** [comment]
You could also use [open3d's remove statistical outlier function](https://www.open3d.org/docs/0.9.0/tutorial/Advanced/pointcloud_outlier_removal.html) to remove these points.

**Comment by pengssy1** [comment]
ok. Thanks!
