### ISSUE TITLE
How to get edge information?

### ISSUE THREAD

**Issue by FranzEricSchneider** [meyerls/PC-Skeletor#3]
This is just a question, not exactly an issue. The starter code is great, and ran immediately. When I look at the output though, for example the `sceleton.ply` file, it appears as points only. One of the important parts of a skeleton is the connectivity information between various points. I'm assuming somewhere in the `skeletor` and `sceleton` variables in the starter code that connectivity information exists? Is there a way to access or view that?

If it exists but just isn't visualized in the ply file I'd be happy to propose some code to visualize those connections, I've done that recently elsewhere.

![Screenshot from 2023-01-28 17-48-11](https://user-images.githubusercontent.com/3709527/215294637-a0b9b294-21fd-485b-8628-bf708174136f.png)

![Screenshot from 2023-01-28 17-48-32](https://user-images.githubusercontent.com/3709527/215294638-0bf1e05c-1d81-42c9-acde-e4656434a1ad.png)

**Comment by meyerls** [comment]
Hi!

currently, the connectivity is not implemented at least not in this repository. In the near future (following weeks) I will add the connectivity code and simplify the graph structure.

**Comment by meyerls** [comment]
Okay, I just added the code for extracting the graph from the point cloud. 

With
```python
 skeleton, graph, skeleton_graph = skeletor.extract(method='Laplacian', config=laplacian_config)
open3d.visualization.draw_geometries([skeleton_graph])
```

you can get the Skeleton points as a point cloud (skeleton), the networkx graph with info about edge, nodes, Adjacency matrix etc. (graph), and finally a line set to visualize with open3d.

Did it work out for you?

If you have any other suggestions to improve the code or usability, feel free to suggest new things!

**Comment by FranzEricSchneider** [comment]
That's awesome, thank you! I'm pretty unfamiliar with how one updates a `pip` package, will the updated version be available with `pip install pc-skeletor` sometime soon or should I figure out how to install this from source and use it that way?
