### ISSUE TITLE
Laplacian edges seem to jump?

### ISSUE THREAD

**Issue by FranzEricSchneider** [meyerls/PC-Skeletor#5]
I was looking at the edges for the skeleton_graph (thanks for #3 by the way) and it looks like the edges are jumping from spot to spot and skipping a lot of the skeleton. Is that intended?

Brown(ish) is the original cloud, blue is the skeleton (contracted points) and green is the skeleton_graph (open3d LineSet)

![Screenshot from 2023-02-05 19-29-59](https://user-images.githubusercontent.com/3709527/216855954-b24c1db5-8c84-44b2-990d-e9accaf2bad0.png)

**Comment by FranzEricSchneider** [comment]
Another example:

![Screenshot from 2023-02-05 19-33-14](https://user-images.githubusercontent.com/3709527/216856148-54366920-67c5-4b5c-95b7-e6ae655d21ef.png)

**Comment by meyerls** [comment]
Hi @FranzEricSchneider,

Sorry for the late response. The green line set is the topological representation of the skeleton. In the next days I will review the documentation and the code to make things more clear. Stay tuned!

**Comment by FranzEricSchneider** [comment]
Is a non-topological set of skeletal lines available that follow the shape better? For the use I was trying this for, for example, the topological lines weren't of use since they don't follow the object shape.

**Comment by meyerls** [comment]
The contracted point cloud can be accessed with ```skeletor.contracted_point_cloud ```. This should be what you are looking for, right? 

In the next update things should get much clearer.

**Comment by meyerls** [comment]
No currently not. I will implement it in the next update!
