### ISSUE TITLE
about the effect of skeleton extraction

### ISSUE THREAD

**Issue by Ameliecc** [meyerls/PC-Skeletor#6]
Hi, @meyerls 
I use your code and run the data of my own, which is a point cloud of cube.  The endpoint of the extracted skeleton line is shorter than that of the origin cloud. I tried to adjust the parameters, but the effect was not very good. Could you give me some advice?
![image](https://user-images.githubusercontent.com/88390612/227750086-08f9fba5-168c-4922-9ab9-ce2990485a72.png)
The blue line is the extracted skeleton.

I hope the skeleton can be as the red line, because I want to calculate the length of the skeleton.
![image](https://user-images.githubusercontent.com/88390612/227750106-1c955791-cf13-4669-a988-78e699b64860.png)

**Comment by meyerls** [comment]
Hi @Ameliecc,

unfortunately, this effect always occurs. This is due to the contraction property of the algorithm. A workaround would be if you get more points at the edges so that the point cloud contracts less in this region.
