### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by lacie-life** [meyerls/pc-skeletor#8]
Thank you for making this code available. After I installed pc-Skeletor from pip,  I met an error when running example:

`skeleton, graph, skeleton_graph = skeletor.extract(method='Laplacian', config=laplacian_config)
ValueError: not enough values to unpack (expected 3, got 2)`

Are you have any suggestions for me?

**Comment by meyerls** [comment]
Hi @lacie-life,

I think I forgot to update all examples during my last change. Nevertheless use the branch s-lbc for a new version. It is a revised version and will be released to pypi in the next weeks.
